---
# tasks file for gitlab_runner
- name: Copy registration gitlab-runner script
  template:
    src: "{{ role_path }}/files/regrunner.sh"
    dest: "/tmp/"
    mode: '0777'
  become: true

- name: Register gitlab-runner
  shell: /tmp/regrunner.sh
  become: true

- name: Gitlab runner add-priveleg-true
  shell: sudo sed -i "30s~.*~    privileged = true~" /etc/gitlab-runner/config.toml

- name: Add passless glrunner
  shell: echo "gitlab-runner ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

- name: Add rh to group 'docker'
  user:
    name: rh
    groups: docker
    append: yes
  become: true

- name: Add gitlab-runner to group 'docker'
  user:
    name: gitlab-runner
    groups: docker
    append: yes
  become: true

- name: Change ownership of /etc/systemd/system
  ansible.builtin.file:
    path: /etc/systemd/system
    state: directory
    recurse: yes
    owner: gitlab-runner
    group: gitlab-runner
  become: true
